- name: Install Apache (Ubuntu)
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"

- name: Install Apache (CentOS)
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"
