- name: Detect OS and set MySQL socket path
  set_fact:
    mysql_socket: >-
      {%- if ansible_os_family == "RedHat" -%}
        /var/lib/mysql/mysql.sock
      {%- elif ansible_os_family == "Debian" -%}
        /run/mysqld/mysqld.sock
      {%- else -%}
        /var/lib/mysql/mysql.sock  # Default fallback
      {%- endif -%}

- name: Install PyMySQL
  become: yes
  package:
    name: python3-PyMySQL
    state: present

- name: Secure MariaDB Installation
  community.mysql.mysql_user:
    name: root
    password: "{{ db_root_password }}"
    host: localhost
    login_password: "{{ db_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    state: present
    update_password: always

- name: Create WordPress Database
  community.mysql.mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"

- name: Create WordPress User with Permissions
  community.mysql.mysql_user:
    name: wordpress_user
    password: "{{ db_user_password }}"
    priv: "wordpress.*:ALL"
    host: '%'
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"

- name: Flush MySQL Privileges
  community.mysql.mysql_query:
    query: "FLUSH PRIVILEGES;"
    login_user: root
    login_password: "{{ db_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"

