- name: Install MariaDB (Ubuntu)
  apt:
    name: mariadb-server
    state: present
  when: ansible_os_family == "Debian"

- name: Install MariaDB (CentOS)
  yum:
    name: mariadb-server
    state: present
  when: ansible_os_family == "RedHat"

- name: Start and Enable MariaDB
  systemd:
    name: mariadb
    state: started
    enabled: yes

