- name: Install PHP and Dependencies (Ubuntu)
  apt:
    name:
      - php
      - php-mysql
      - libapache2-mod-php
    state: present
  when: ansible_os_family == "Debian"

- name: Install PHP and Dependencies (CentOS)
  yum:
    name:
      - php
      - php-mysqlnd
      - php-fpm
    state: present
  when: ansible_os_family == "RedHat"

